---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-redis-data
  namespace: dify
  labels:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
