---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-db-data
  namespace: dify
  labels:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
