---
apiVersion: v1
kind: Service
metadata:
  name: ssrf-proxy
  namespace: dify
  labels:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: ssrf-proxy
spec:
  type: ClusterIP
  ports:
  - name: proxy
    port: 3128
    targetPort: 3128
    protocol: TCP
  selector:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: ssrf-proxy
