---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dify
  labels:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: nginx
