---
apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: dify
  labels:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: sandbox
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8194
    targetPort: 8194
    protocol: TCP
  selector:
    app.kubernetes.io/name: dify
    app.kubernetes.io/component: sandbox
